-- MySQL Script generated by MySQL Workbench
-- уторак, 08. јануар 2019. 18:28:41 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema veleprodaja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `veleprodaja` ;

-- -----------------------------------------------------
-- Schema veleprodaja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veleprodaja` DEFAULT CHARACTER SET utf8 ;
USE `veleprodaja` ;

-- -----------------------------------------------------
-- Table `veleprodaja`.`Zaposleni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Zaposleni` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Zaposleni` (
  `idZaposleni` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ImePrezime` VARCHAR(45) NULL,
  `DatumZaposlenja` DATE NULL,
  `StručnaSprema` VARCHAR(45) NULL,
  `Funkcija` VARCHAR(45) NULL,
  `UgovorenaPlata` VARCHAR(45) NULL,
  `KorisnickoIme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZaposleni`, `KorisnickoIme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`KupciDobavljaci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`KupciDobavljaci` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`KupciDobavljaci` (
  `idKD` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PIB` INT NULL,
  `NazivFirme` VARCHAR(45) NULL,
  `TekućiRačun` VARCHAR(45) NULL,
  PRIMARY KEY (`idKD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Kontakt_osoba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Kontakt_osoba` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Kontakt_osoba` (
  `idKontOsobe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idKD` INT UNSIGNED NOT NULL,
  `ImePrezime` INT NULL,
  `Telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`idKontOsobe`, `idKD`),
  CONSTRAINT `fk_Kontakt osoba_Kupac`
    FOREIGN KEY (`idKD`)
    REFERENCES `veleprodaja`.`KupciDobavljaci` (`idKD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Dokument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Dokument` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Dokument` (
  `idDokument` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `VremeKreiranja` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `VremeIzmene` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `IzmenaKorisnik` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`idDokument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`PorudzbinaNarudzbina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`PorudzbinaNarudzbina` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`PorudzbinaNarudzbina` (
  `idPN` INT UNSIGNED NOT NULL,
  `idKD` INT UNSIGNED NOT NULL,
  `DatumPorudzbine` DATE NULL,
  INDEX `fk_Zaposleni_has_Kupac_Kupac1_idx` (`idKD` ASC),
  PRIMARY KEY (`idPN`),
  CONSTRAINT `fk_Zaposleni_has_Kupac_Kupac1`
    FOREIGN KEY (`idKD`)
    REFERENCES `veleprodaja`.`KupciDobavljaci` (`idKD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Porudžbina_1`
    FOREIGN KEY (`idPN`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Proizvod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Proizvod` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Proizvod` (
  `idProizvodi` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NULL,
  `Cena` DECIMAL NULL,
  PRIMARY KEY (`idProizvodi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Stavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Stavka` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Stavka` (
  `idDokumenta` INT UNSIGNED NOT NULL,
  `Proizvodi_idProizvodi` INT UNSIGNED NOT NULL,
  `Kolicina` INT NULL,
  `Cena` DECIMAL NULL,
  PRIMARY KEY (`idDokumenta`, `Proizvodi_idProizvodi`),
  INDEX `fk_Stavke_Proizvodi1_idx` (`Proizvodi_idProizvodi` ASC),
  CONSTRAINT `fk_Stavke_Proizvodi1`
    FOREIGN KEY (`Proizvodi_idProizvodi`)
    REFERENCES `veleprodaja`.`Proizvod` (`idProizvodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dokument`
    FOREIGN KEY (`idDokumenta`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Proizvod_has_Proizvod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Proizvod_has_Proizvod` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Proizvod_has_Proizvod` (
  `Proizvod_idProizvodi` INT UNSIGNED NOT NULL,
  `Proizvod_idProizvodi1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Proizvod_idProizvodi`, `Proizvod_idProizvodi1`),
  INDEX `fk_Proizvod_has_Proizvod_Proizvod2_idx` (`Proizvod_idProizvodi1` ASC),
  INDEX `fk_Proizvod_has_Proizvod_Proizvod1_idx` (`Proizvod_idProizvodi` ASC),
  CONSTRAINT `fk_Proizvod_has_Proizvod_Proizvod1`
    FOREIGN KEY (`Proizvod_idProizvodi`)
    REFERENCES `veleprodaja`.`Proizvod` (`idProizvodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proizvod_has_Proizvod_Proizvod2`
    FOREIGN KEY (`Proizvod_idProizvodi1`)
    REFERENCES `veleprodaja`.`Proizvod` (`idProizvodi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Ponuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Ponuda` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Ponuda` (
  `idPonuda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPN` INT UNSIGNED NOT NULL,
  `DatumPonude` DATE NULL,
  `Kontinuitet_broj_isporuka` VARCHAR(45) NULL,
  `Nacin_isporuke` VARCHAR(45) NULL,
  `Rok_placanja` DATE NULL,
  `Cena` DECIMAL NULL,
  `Popust` DECIMAL NULL,
  `Prodajna_cena` DECIMAL NULL,
  PRIMARY KEY (`idPonuda`),
  INDEX `fk_Ponuda_Porudžbina1_idx` (`idPN` ASC),
  CONSTRAINT `fk_Ponuda_Porudžbina1`
    FOREIGN KEY (`idPN`)
    REFERENCES `veleprodaja`.`PorudzbinaNarudzbina` (`idPN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ponuda_1`
    FOREIGN KEY (`idPonuda`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`OtpremnicaPrijemnica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`OtpremnicaPrijemnica` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`OtpremnicaPrijemnica` (
  `idOtpremnica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idMagacina` VARCHAR(45) NULL,
  `Ponuda_idPonuda` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idOtpremnica`),
  INDEX `fk_Otpremnica_Ponuda1_idx` (`Ponuda_idPonuda` ASC),
  CONSTRAINT `fk_Otpremnica_Ponuda1`
    FOREIGN KEY (`Ponuda_idPonuda`)
    REFERENCES `veleprodaja`.`Ponuda` (`idPonuda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Otpremnica_1`
    FOREIGN KEY (`idOtpremnica`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`FakturaIzlazna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`FakturaIzlazna` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`FakturaIzlazna` (
  `idFakIzlaz` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Otpremnica_idOtpremnica` INT UNSIGNED NOT NULL,
  `Rok isporuke` DATE NULL,
  PRIMARY KEY (`idFakIzlaz`),
  INDEX `fk_Faktura_Otpremnica1_idx` (`Otpremnica_idOtpremnica` ASC),
  CONSTRAINT `fk_Faktura_Otpremnica1`
    FOREIGN KEY (`Otpremnica_idOtpremnica`)
    REFERENCES `veleprodaja`.`OtpremnicaPrijemnica` (`idOtpremnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faktura_1`
    FOREIGN KEY (`idFakIzlaz`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`Izradjuje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`Izradjuje` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`Izradjuje` (
  `Dokument_idDokument` INT UNSIGNED NOT NULL,
  `Zaposleni_idZaposleni` INT UNSIGNED NOT NULL,
  `Zaposleni_KorisnickoIme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dokument_idDokument`, `Zaposleni_idZaposleni`, `Zaposleni_KorisnickoIme`),
  INDEX `fk_Zaposleni_has_Dokument_Dokument1_idx` (`Dokument_idDokument` ASC),
  INDEX `fk_Zaposleni_has_Dokument_Zaposleni1_idx` (`Zaposleni_idZaposleni` ASC, `Zaposleni_KorisnickoIme` ASC),
  CONSTRAINT `fk_Zaposleni_has_Dokument_Zaposleni1`
    FOREIGN KEY (`Zaposleni_idZaposleni` , `Zaposleni_KorisnickoIme`)
    REFERENCES `veleprodaja`.`Zaposleni` (`idZaposleni` , `KorisnickoIme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaposleni_has_Dokument_Dokument1`
    FOREIGN KEY (`Dokument_idDokument`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veleprodaja`.`FakturaUlazna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veleprodaja`.`FakturaUlazna` ;

CREATE TABLE IF NOT EXISTS `veleprodaja`.`FakturaUlazna` (
  `idFakUlaz` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Otpremnica_idOtpremnica` INT UNSIGNED NOT NULL,
  `Rok isporuke` DATE NULL,
  PRIMARY KEY (`idFakUlaz`),
  INDEX `fk_Faktura_Otpremnica1_idx` (`Otpremnica_idOtpremnica` ASC),
  CONSTRAINT `fk_Faktura_Otpremnica10`
    FOREIGN KEY (`Otpremnica_idOtpremnica`)
    REFERENCES `veleprodaja`.`OtpremnicaPrijemnica` (`idOtpremnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faktura_10`
    FOREIGN KEY (`idFakUlaz`)
    REFERENCES `veleprodaja`.`Dokument` (`idDokument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TRIGGER IF EXISTS insPor;
DELIMITER $$
CREATE TRIGGER insPor BEFORE INSERT ON PorudzbinaNarudzbina
  FOR EACH ROW
    begin

    -- uzimo dostupan id iz tabele dokument
    SET NEW.idPN = (SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'veleprodaja' AND   TABLE_NAME   = 'Dokument');

    -- kreiramo odgovarajucu torku u dokumentu
    INSERT INTO Dokument(VremeKreiranja,VremeIzmene,IzmenaKorisnik,Status)
    VALUES (current_timestamp,current_timestamp,USER(),'radni');
    
    -- unosi podatke o useru koji je ubacio porudzbinu
    INSERT INTO Izradjuje VALUES (NEW.idPN,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS insPon;
DELIMITER $$
CREATE TRIGGER insPon BEFORE INSERT ON Ponuda
  FOR EACH ROW
    begin

    SET NEW.idPonuda = (SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'veleprodaja' AND   TABLE_NAME   = 'Dokument');
    
    INSERT INTO Dokument(VremeKreiranja,VremeIzmene,IzmenaKorisnik,Status)
    VALUES (current_timestamp,current_timestamp,USER(),'radni');

    
    INSERT INTO Izradjuje VALUES (NEW.idPonuda,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS insOtp;
DELIMITER $$
CREATE TRIGGER insOtp BEFORE INSERT ON OtpremnicaPrijemnica
  FOR EACH ROW
    begin

    SET NEW.idOtpremnica = (SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'veleprodaja' AND   TABLE_NAME   = 'Dokument');
    
    INSERT INTO Dokument(VremeKreiranja,VremeIzmene,IzmenaKorisnik,Status)
    VALUES (current_timestamp,current_timestamp,USER(),'radni');
    
    INSERT INTO Izradjuje VALUES (NEW.idOtpremnica,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS insFakIz;
DELIMITER $$
CREATE TRIGGER insFakIz BEFORE INSERT ON FakturaIzlazna
  FOR EACH ROW
    begin

    SET NEW.idFakIzlaz = (SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'veleprodaja' AND   TABLE_NAME   = 'Dokument');
    
    INSERT INTO Dokument(VremeKreiranja,VremeIzmene,IzmenaKorisnik,Status)
    VALUES (current_timestamp,current_timestamp,USER(),'radni');
    
    INSERT INTO Izradjuje VALUES (NEW.idFakIzlaz,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS insFakUl;
DELIMITER $$
CREATE TRIGGER insFakUl BEFORE INSERT ON FakturaUlazna
  FOR EACH ROW
    begin

    SET NEW.idFakUlaz = (SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'veleprodaja' AND   TABLE_NAME   = 'Dokument');
    
    INSERT INTO Dokument(VremeKreiranja,VremeIzmene,IzmenaKorisnik,Status)
    VALUES (current_timestamp,current_timestamp,USER(),'radni');
    
    INSERT INTO Izradjuje VALUES (NEW.idFakUlaz,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updPor;
DELIMITER $$
CREATE TRIGGER updPor BEFORE UPDATE ON PorudzbinaNarudzbina
  FOR EACH ROW
    begin

    -- ako se update porudzbina update i dokument
    UPDATE Dokument SET VremeIzmene = current_timestamp, IzmenaKorisnik = USER() WHERE NEW.idPN = idDokument;
    
    -- evidentiramo ako je neki drugi user vrsio izmene
    INSERT IGNORE INTO Izradjuje VALUES (NEW.idPN,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updPon;
DELIMITER $$
CREATE TRIGGER updPon BEFORE UPDATE ON Ponuda
  FOR EACH ROW
    begin

    UPDATE Dokument SET VremeIzmene = current_timestamp, IzmenaKorisnik = USER() WHERE NEW.idPonuda = idDokument;
    
    INSERT IGNORE INTO Izradjuje VALUES (NEW.idPonuda,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;
 
DROP TRIGGER IF EXISTS updOtp;
DELIMITER $$
CREATE TRIGGER updOtp BEFORE UPDATE ON OtpremnicaPrijemnica
  FOR EACH ROW
    begin

    UPDATE Dokument SET VremeIzmene = current_timestamp, IzmenaKorisnik = USER() WHERE NEW.idOtpremnica = idDokument;
    
    INSERT IGNORE INTO Izradjuje VALUES (NEW.idOtpremnica,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updFakIz;
DELIMITER $$
CREATE TRIGGER updFakIz BEFORE UPDATE ON FakturaIzlazna
  FOR EACH ROW
    begin

    UPDATE Dokument SET VremeIzmene = current_timestamp, IzmenaKorisnik = USER() WHERE NEW.idFakIzlaz = idDokument;
    
    INSERT IGNORE INTO Izradjuje VALUES (NEW.idFakIzlaz,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updFakUl;
DELIMITER $$
CREATE TRIGGER updFakUl BEFORE UPDATE ON FakturaUlazna
  FOR EACH ROW
    begin

    UPDATE Dokument SET VremeIzmene = current_timestamp, IzmenaKorisnik = USER() WHERE NEW.idFakUlaz = idDokument;
    
    INSERT IGNORE INTO Izradjuje VALUES (NEW.idFakUlaz,(SELECT idZaposleni from Zaposleni WHERE KorisnickoIme = USER()),USER());
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS insStavka;
DELIMITER $$
CREATE TRIGGER insStavka BEFORE INSERT ON Stavka
  FOR EACH ROW
    begin
    
    -- cena stavke na osnovu kolicine i cene proizvoda
    SET NEW.Cena = NEW.Kolicina * (SELECT Cena FROM Proizvod WHERE Proizvod.idProizvodi = NEW.Proizvodi_idProizvodi);
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updStavka;
DELIMITER $$
CREATE TRIGGER updStavka BEFORE UPDATE ON Stavka
  FOR EACH ROW
    begin
    
    SET NEW.Cena = NEW.Kolicina * (SELECT Cena FROM Proizvod WHERE Proizvod.idProizvodi = NEW.Proizvodi_idProizvodi);
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS insAftStavka;
DELIMITER $$
CREATE TRIGGER insAftStavka AFTER INSERT ON Stavka
  FOR EACH ROW
    begin
    
    -- cena ponuda je zbir cena stavki u toj ponudi
    UPDATE Ponuda SET Cena = (SELECT SUM(Cena) from Stavka WHERE Stavka.idDokumenta = idPonuda)
    WHERE idPonuda = NEW.idDokumenta;
    
    -- racuna se i prodajna cena, u koju se ukljucuje eventualni popust
    UPDATE Ponuda SET Prodajna_cena = Ponuda.Cena - (Ponuda.Popust * 0.01 ) * Ponuda.Cena
    WHERE idPonuda = NEW.idDokumenta;
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updAftStavka;
DELIMITER $$
CREATE TRIGGER updAftStavka AFTER UPDATE ON Stavka
  FOR EACH ROW
    begin
    
    UPDATE Ponuda SET Cena = (SELECT SUM(Cena) FROM Stavka WHERE Stavka.idDokumenta = idPonuda)
    WHERE idPonuda = NEW.idDokumenta;
    
    UPDATE Ponuda SET Prodajna_cena = Ponuda.Cena - (Ponuda.Popust * 0.01 ) * Ponuda.Cena
    WHERE idPonuda = NEW.idDokumenta;
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS delAftStavka;
DELIMITER $$
CREATE TRIGGER delAftStavka AFTER DELETE ON Stavka
  FOR EACH ROW
    begin
    
    -- cena ponuda je zbir cena stavki u toj ponudi
    UPDATE Ponuda SET Cena = (SELECT SUM(Cena) from Stavka WHERE Stavka.idDokumenta = idPonuda)
    WHERE idPonuda = OLD.idDokumenta;
    
    -- racuna se i prodajna cena, u koju se ukljucuje eventualni popust
    UPDATE Ponuda SET Prodajna_cena = Ponuda.Cena - (Ponuda.Popust * 0.01 ) * Ponuda.Cena
    WHERE idPonuda = OLD.idDokumenta;
    
    end$$
    
DELIMITER ;

DROP TRIGGER IF EXISTS updAftPonuda;
DELIMITER $$
CREATE TRIGGER updAftPonuda BEFORE UPDATE ON Ponuda
  FOR EACH ROW
    begin
    
    -- u slucaju ako update popust recimo
    SET NEW.Prodajna_cena = NEW.Cena - (NEW.Popust * 0.01 ) * NEW.Cena;
    
    end$$
    
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
